### PR TITLE
Add automatic translations with google

### PR DESCRIPTION
**Pull request by haringsrob**
Hi,

This is a proposal pr for adding google translate as an automatic translation service.

While the pr needs still a lot of work I wanted to share this draft so we can discuss if it is something good or not for this project.

I have never worked with typescript, I did my best to follow conventions but sorry if I missed out on things.

There are quite some todo's inline that further describe the idea, potential issues and improvements that can be done.

Thank you for this awesome project!

### CODE REVIEW

**Comment by anthonynsimon** [comment]
Hey this looks awesome! Thanks for proposing these changes, I will checkout the code in the coming days.

Btw regarding marking the translations as "machine translated", you could use the tagging feature to add some tags automatically to those translations if that's what you're looking for. Should be pretty straightforward.

**Comment by haringsrob** [comment]
Ah that is an interesting take indeed. I will check that out.

**Comment by arelstone** [comment]
This is awesome.. Just what I need for my project. Already created an issue for this #156

**Comment by fnowacki** [comment]
@anthonynsimon what about this PR? :)

**Comment by anthonynsimon** [comment]
@fnowacki  I think this feature is great! However, I see many TODO's still open in the changes - would have to wait for those before merging :)

**Comment by haringsrob** [comment]
I personally do not have much time at the moment to focus on this. I think the pr is open for changes :).

**Comment by anthonynsimon** [comment]
@haringsrob thanks for the update, and no worries - I understand :)

**Comment by arelstone** [comment]
Would be great if we could get someone to finish this. Really looking forward to this feature

**Comment by Alex-Giaquinto** [comment]
Has this every been implemented?

**Comment by evereq** [comment]
@Alex-Giaquinto / @fnowacki  afraid it was not implemented. The PR indeed have a lot of TODOs that need to be resolved/improved etc. In addition, there are many more automatic translation options now, e.g. including OpenAI API, etc. I think we will need an approach with "providers" that allow translation services and implement that with some sort of plugin infrastructure, e.g. "Google Translate Plugin", "OpenAI Translate Plugin", etc. So it requires more work...

**Pull request closed without merging**
