### PR TITLE
Add support to docker secrets

### PR DESCRIPTION
**Pull request by ynuyasha**
### Before submitting the PR, please make sure you do the following

 1. Contributor license agreement
For us it's important to have the agreement of our contributors to use their work, whether it be code or documentation. Therefore, we are asking all contributors to sign a contributor license agreement (CLA) as commonly accepted in most open source projects. **Just open the pull request and our CLA bot will prompt you briefly.**

 2. Please check our [contribution guidelines](https://docs.traduora.com/docs/contributing#review-process-for-this-repo) for some help in the process.

### CODE REVIEW

**Comment by evereq** [comment]
Hi @ynuyasha  thank you for the PR. 

It makes total sense for me. 
The only thing I worry about a bit is that it's "inspired from MySQL docker_entrypoint" (https://github.com/docker-library/mysql/blob/master/5.6/docker-entrypoint.sh), which have a different license (GPL v2) to our (AGPL v3). 
I will need to check that and if all is good, will merge PR.

**Comment by ynuyasha** [comment]
What you think if you open an issue about this on docker-library?
Because they suggest to use this approach inside documentation https://docs.docker.com/engine/swarm/secrets/#build-support-for-docker-secrets-into-your-images

**Comment by evereq** [comment]
@ynuyasha it's not about approach, it's only about reuse of code from other repos (projects). If you will implement it yourself or found some code that is MIT or GPL v3 licensed, we don't have a problem including it here.  We just can't include GPL v2 ("only") code in our repos :)

**Comment by evereq** [comment]
Btw, @ynuyasha I don't think they will change the license from GPL v2 to "GPL v2 and any later version", even if we will ask, because "Upstream's license is complicated" :(

**Comment by ynuyasha** [comment]
Hi @evereq , i have opened a question inside docker library https://github.com/docker-library/mysql/issues/772 and they told me that you can include code into gpl3 and the same code is already redestribuite under other licences please ready it

**Comment by evereq** [comment]
@ynuyasha think we can merge PR if you will tell that you copied that code from say https://github.com/docker-library/rabbitmq/blob/master/docker-entrypoint.sh release under MIT :) 

Can you say that? And add please to the file `docker-entrypoint.sh`  the following statement at the top of the file:

// From https://github.com/docker-library/rabbitmq/blob/master/docker-entrypoint.sh
// MIT License https://github.com/docker-library/rabbitmq/blob/master/LICENSE
// Copyright (c) 2014 Docker, Inc.

Thank you in advance ;)

**Comment by ynuyasha** [comment]
Hi @evereq i have changed a little bit, because i forgot that file_env function not working on /bin/sh shell, so is very strange that your test was green https://app.circleci.com/pipelines/github/ever-co/ever-traduora/437/workflows/b17852be-85a2-45c3-a465-ff3427d80d66/jobs/489, maybe is because not testing this feature?
With this new version is still valid mention rabbitmq work?

**Pull request merged**
