### PR TITLE
Feature/138 resx

### PR DESCRIPTION
**Pull request by rai69**
Support for Resource ResX files added.

- New formatter add (parser and exporter)
- Added ResX to import and export list.

### CODE REVIEW

**Comment by rai69** [comment]
Two tests are failing, with respect to yaml-nested.spec.ts. I didn't change anything in that part. Please advice on how to continu?

**Comment by evereq** [comment]
@rai69 thanks for your contribution! 🚀 

Yeah, both tests are failed before your changes, we not sure why, our developer tried to fix it but can't make it work for now...
(if you can help with that, we will appreciate it so much!)

Thanks again, I am merging PR now!

**Comment by rai69** [comment]
@evereq The problem comes from the upgrade from js-yaml (3:13 => 4.1). There the colon (:) is now excluded from being a special character. I couldn't find a fix. Perhaps we can reverse the upgrade for now?

**Comment by evereq** [comment]
@rai69 hm, I am not so sure that it's an issue with the library... 
Tried on http://nodeca.github.io/js-yaml/#yaml=dGVybToKICBvbmU6ICdDdXJyZW50IFBsYW46IHt7IHByb2plY3QucGxhbi5uYW1lIH19Jwp0ZXJtIHR3bzogJ3tWQVJfUExVUkFMLCBwbHVyYWwsID0wIHtsb2NhbGVzfSA9MSB7bG9jYWxlfSBvdGhlciB7bG9jYWxlc30gfScKVEVSTV9USFJFRTogRXhwb3J0IGZvcm1hdC4uLgondGVybTpmb3VyJzogaGVsbG8gdGhlcmUgeW91XG50aGlzIHNob3VsZCBiZSBpbiBhIG5ld2xpbmU= and it worked well:
image

I also tried to install lib locally (latest version via npm) and it also worked fine:

`yo.yaml` content
```
term:
  one: 'Current Plan: {{ project.plan.name }}'
term two: '{VAR_PLURAL, plural, =0 {locales} =1 {locale} other {locales} }'
TERM_THREE: Export format...
'term:four': hello there you\nthis should be in a newline
```

```
js-yaml yo.yaml

{
  "term": {
    "one": "Current Plan: {{ project.plan.name }}"
  },
  "term two": "{VAR_PLURAL, plural, =0 {locales} =1 {locale} other {locales} }",
  "TERM_THREE": "Export format...",
  "term:four": "hello there you\\nthis should be in a newline"
}
```

More like it's some issues in our code, possible in the way we process input for the library?

CC: @rahul-rathore-576

**Comment by rai69** [comment]
@evereq The test fails in the case yaml => json. There is also where the change is in de js-yaml. (https://github.com/nodeca/js-yaml/blob/master/CHANGELOG.md) 
`dump() no longer quotes :, [, ], (, ) except when necessary, #470, #557.`

This change has the following affect:
Old situation:
`{ "term:four" : "hello there you\\nthis should be in a newline" } => 'term:four': "hello there you\\nthis should be in a newline"`
New situation:
`{ "term:four" : "hello there you\\nthis should be in a newline" } => term:four: "hello there you\\nthis should be in a newline"`

The tests expect the quotes to be present. Seeing that without the quotes the yaml is still valid, we could remove the quotes from the fixture file. This could however be a breaking change for users of the the Traduora tool.

**Comment by evereq** [comment]
@rai69 I also thought that way before I did tests mentioned in the https://github.com/ever-co/ever-traduora/pull/222#issuecomment-847054345. Such tests show that latest library version actually handles everything as it should. I.e. what you describe as "New situation" seems did not happen because of the library. This is the output of the library when used not from our code:

```
  "term:four": "hello there you\\nthis should be in a newline"
```

So the library seems do have quotes symbol around key "term:four" (because it tells "except when necessary" and it IS necessary for such keys with ":" symbol inside to keep quotes around it)

So I still not sure from where the issue comes from, but unlikely from library itself... Think we need to look deeply to see what happens in our code that uses lib

**Comment by rai69** [comment]
@evereq I was under the impression that the test that you did was from yaml to json. But the test that fails is from json to yaml.

**Pull request merged**
