### PR TITLE
Feat: add postgresql as db

### LINKED ISSUE #390: [Feature] Ability to use PostgreSQL
**Is your feature request related to a problem? Please describe.**

Add the ability to use PostgreSQL in addition to MySQL

### PR DESCRIPTION
**Pull request by vvadymk**
This PR resolves #390 by using a postgreSQL as a db.

### CODE REVIEW

**Comment by vvadymk** [comment]
Hi @evereq!
As we have discussed about postgresql in the previous pr I created a pr with my changes to support this db.

**Comment by vvadymk** [comment]
@evereq thank you for the review. I could do it by myself and push into this pr. I also will fix failed tests.

**Comment by vvadymk** [comment]
Hi @evereq! this task is in progress and it isn't forgotten. I will try to finish it on weekends

**Comment by vvadymk** [comment]
@evereq I have pushed feature that the Traduora could work either with PostgreSQL or with MySQL.

**Comment by evereq** [comment]
Thank you so much @vvadymk, I will review it over the next few days and get back! (got a bit sick, and needs to recover)

**Comment by vvadymk** [comment]
@evereq I wish you the fastest get well!

**Pull request merged**
